server:
  port: 8989
spring:
  application.name: ReportApplication
  datasource.driver-class-name: org.apache.phoenix.jdbc.PhoenixDriver
  datasource.url: jdbc:phoenix:node-etl-01:2181
  datasource.type: com.alibaba.druid.pool.DruidDataSource
#指定mybatis映射文件的地址
mybatis:
  mapper-locations: classpath:mapper/*.xml
